version: '3.9'

services:
  postgres:
    image: postgres
    container_name: mypostgresdb
    environment:
      POSTGRES_DB: DesafioRodonaves
      POSTGRES_USER: rodonaves
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"